/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.shl.thriftstudy.service;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ShlShopBooking {

  public interface Iface extends com.facebook.fb303.FacebookService.Iface {

    public com.shl.thriftstudy.result.BookingResult shlbooking(com.shl.thriftstudy.param.BookingModel bookingModel) throws org.apache.thrift.TException;

  }

  public interface AsyncIface extends com.facebook.fb303.FacebookService .AsyncIface {

    public void shlbooking(com.shl.thriftstudy.param.BookingModel bookingModel, org.apache.thrift.async.AsyncMethodCallback<AsyncClient.shlbooking_call> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends com.facebook.fb303.FacebookService.Client implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public com.shl.thriftstudy.result.BookingResult shlbooking(com.shl.thriftstudy.param.BookingModel bookingModel) throws org.apache.thrift.TException
    {
      send_shlbooking(bookingModel);
      return recv_shlbooking();
    }

    public void send_shlbooking(com.shl.thriftstudy.param.BookingModel bookingModel) throws org.apache.thrift.TException
    {
      shlbooking_args args = new shlbooking_args();
      args.setBookingModel(bookingModel);
      sendBase("shlbooking", args);
    }

    public com.shl.thriftstudy.result.BookingResult recv_shlbooking() throws org.apache.thrift.TException
    {
      shlbooking_result result = new shlbooking_result();
      receiveBase(result, "shlbooking");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "shlbooking failed: unknown result");
    }

  }
  public static class AsyncClient extends com.facebook.fb303.FacebookService.AsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void shlbooking(com.shl.thriftstudy.param.BookingModel bookingModel, org.apache.thrift.async.AsyncMethodCallback<shlbooking_call> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      shlbooking_call method_call = new shlbooking_call(bookingModel, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class shlbooking_call extends org.apache.thrift.async.TAsyncMethodCall {
      private com.shl.thriftstudy.param.BookingModel bookingModel;
      public shlbooking_call(com.shl.thriftstudy.param.BookingModel bookingModel, org.apache.thrift.async.AsyncMethodCallback<shlbooking_call> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.bookingModel = bookingModel;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("shlbooking", org.apache.thrift.protocol.TMessageType.CALL, 0));
        shlbooking_args args = new shlbooking_args();
        args.setBookingModel(bookingModel);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public com.shl.thriftstudy.result.BookingResult getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_shlbooking();
      }
    }

  }

  public static class Processor<I extends Iface> extends com.facebook.fb303.FacebookService.Processor implements org.apache.thrift.TProcessor {
    private static final Logger LOGGER = LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new HashMap<String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> getProcessMap(Map<String,  org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("shlbooking", new shlbooking());
      return processMap;
    }

    private static class shlbooking<I extends Iface> extends org.apache.thrift.ProcessFunction<I, shlbooking_args> {
      public shlbooking() {
        super("shlbooking");
      }

      protected shlbooking_args getEmptyArgsInstance() {
        return new shlbooking_args();
      }

      protected shlbooking_result getResult(I iface, shlbooking_args args) throws org.apache.thrift.TException {
        shlbooking_result result = new shlbooking_result();
        result.success = iface.shlbooking(args.bookingModel);
        return result;
      }
    }

  }

  public static class shlbooking_args implements org.apache.thrift.TBase<shlbooking_args, shlbooking_args._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("shlbooking_args");

    private static final org.apache.thrift.protocol.TField BOOKING_MODEL_FIELD_DESC = new org.apache.thrift.protocol.TField("bookingModel", org.apache.thrift.protocol.TType.STRUCT, (short)1);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new shlbooking_argsStandardSchemeFactory());
      schemes.put(TupleScheme.class, new shlbooking_argsTupleSchemeFactory());
    }

    public com.shl.thriftstudy.param.BookingModel bookingModel; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      BOOKING_MODEL((short)1, "bookingModel");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // BOOKING_MODEL
            return BOOKING_MODEL;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.BOOKING_MODEL, new org.apache.thrift.meta_data.FieldMetaData("bookingModel", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.shl.thriftstudy.param.BookingModel.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(shlbooking_args.class, metaDataMap);
    }

    public shlbooking_args() {
    }

    public shlbooking_args(
      com.shl.thriftstudy.param.BookingModel bookingModel)
    {
      this();
      this.bookingModel = bookingModel;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public shlbooking_args(shlbooking_args other) {
      if (other.isSetBookingModel()) {
        this.bookingModel = new com.shl.thriftstudy.param.BookingModel(other.bookingModel);
      }
    }

    public shlbooking_args deepCopy() {
      return new shlbooking_args(this);
    }

    @Override
    public void clear() {
      this.bookingModel = null;
    }

    public com.shl.thriftstudy.param.BookingModel getBookingModel() {
      return this.bookingModel;
    }

    public shlbooking_args setBookingModel(com.shl.thriftstudy.param.BookingModel bookingModel) {
      this.bookingModel = bookingModel;
      return this;
    }

    public void unsetBookingModel() {
      this.bookingModel = null;
    }

    /** Returns true if field bookingModel is set (has been assigned a value) and false otherwise */
    public boolean isSetBookingModel() {
      return this.bookingModel != null;
    }

    public void setBookingModelIsSet(boolean value) {
      if (!value) {
        this.bookingModel = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case BOOKING_MODEL:
        if (value == null) {
          unsetBookingModel();
        } else {
          setBookingModel((com.shl.thriftstudy.param.BookingModel)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case BOOKING_MODEL:
        return getBookingModel();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case BOOKING_MODEL:
        return isSetBookingModel();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof shlbooking_args)
        return this.equals((shlbooking_args)that);
      return false;
    }

    public boolean equals(shlbooking_args that) {
      if (that == null)
        return false;

      boolean this_present_bookingModel = true && this.isSetBookingModel();
      boolean that_present_bookingModel = true && that.isSetBookingModel();
      if (this_present_bookingModel || that_present_bookingModel) {
        if (!(this_present_bookingModel && that_present_bookingModel))
          return false;
        if (!this.bookingModel.equals(that.bookingModel))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(shlbooking_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      shlbooking_args typedOther = (shlbooking_args)other;

      lastComparison = Boolean.valueOf(isSetBookingModel()).compareTo(typedOther.isSetBookingModel());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetBookingModel()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bookingModel, typedOther.bookingModel);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
    }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("shlbooking_args(");
      boolean first = true;

      sb.append("bookingModel:");
      if (this.bookingModel == null) {
        sb.append("null");
      } else {
        sb.append(this.bookingModel);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class shlbooking_argsStandardSchemeFactory implements SchemeFactory {
      public shlbooking_argsStandardScheme getScheme() {
        return new shlbooking_argsStandardScheme();
      }
    }

    private static class shlbooking_argsStandardScheme extends StandardScheme<shlbooking_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, shlbooking_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // BOOKING_MODEL
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.bookingModel = new com.shl.thriftstudy.param.BookingModel();
                struct.bookingModel.read(iprot);
                struct.setBookingModelIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, shlbooking_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.bookingModel != null) {
          oprot.writeFieldBegin(BOOKING_MODEL_FIELD_DESC);
          struct.bookingModel.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class shlbooking_argsTupleSchemeFactory implements SchemeFactory {
      public shlbooking_argsTupleScheme getScheme() {
        return new shlbooking_argsTupleScheme();
      }
    }

    private static class shlbooking_argsTupleScheme extends TupleScheme<shlbooking_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, shlbooking_args struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetBookingModel()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetBookingModel()) {
          struct.bookingModel.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, shlbooking_args struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.bookingModel = new com.shl.thriftstudy.param.BookingModel();
          struct.bookingModel.read(iprot);
          struct.setBookingModelIsSet(true);
        }
      }
    }

  }

  public static class shlbooking_result implements org.apache.thrift.TBase<shlbooking_result, shlbooking_result._Fields>, java.io.Serializable, Cloneable   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("shlbooking_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRUCT, (short)0);

    private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
    static {
      schemes.put(StandardScheme.class, new shlbooking_resultStandardSchemeFactory());
      schemes.put(TupleScheme.class, new shlbooking_resultTupleSchemeFactory());
    }

    public com.shl.thriftstudy.result.BookingResult success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

      static {
        for (_Fields field : EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final String _fieldName;

      _Fields(short thriftId, String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, com.shl.thriftstudy.result.BookingResult.class)));
      metaDataMap = Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(shlbooking_result.class, metaDataMap);
    }

    public shlbooking_result() {
    }

    public shlbooking_result(
      com.shl.thriftstudy.result.BookingResult success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public shlbooking_result(shlbooking_result other) {
      if (other.isSetSuccess()) {
        this.success = new com.shl.thriftstudy.result.BookingResult(other.success);
      }
    }

    public shlbooking_result deepCopy() {
      return new shlbooking_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public com.shl.thriftstudy.result.BookingResult getSuccess() {
      return this.success;
    }

    public shlbooking_result setSuccess(com.shl.thriftstudy.result.BookingResult success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((com.shl.thriftstudy.result.BookingResult)value);
        }
        break;

      }
    }

    public Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new IllegalStateException();
    }

    @Override
    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof shlbooking_result)
        return this.equals((shlbooking_result)that);
      return false;
    }

    public boolean equals(shlbooking_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      return 0;
    }

    public int compareTo(shlbooking_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;
      shlbooking_result typedOther = (shlbooking_result)other;

      lastComparison = Boolean.valueOf(isSetSuccess()).compareTo(typedOther.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, typedOther.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
      }

    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder("shlbooking_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class shlbooking_resultStandardSchemeFactory implements SchemeFactory {
      public shlbooking_resultStandardScheme getScheme() {
        return new shlbooking_resultStandardScheme();
      }
    }

    private static class shlbooking_resultStandardScheme extends StandardScheme<shlbooking_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, shlbooking_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.success = new com.shl.thriftstudy.result.BookingResult();
                struct.success.read(iprot);
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, shlbooking_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          struct.success.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class shlbooking_resultTupleSchemeFactory implements SchemeFactory {
      public shlbooking_resultTupleScheme getScheme() {
        return new shlbooking_resultTupleScheme();
      }
    }

    private static class shlbooking_resultTupleScheme extends TupleScheme<shlbooking_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, shlbooking_result struct) throws org.apache.thrift.TException {
        TTupleProtocol oprot = (TTupleProtocol) prot;
        BitSet optionals = new BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          struct.success.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, shlbooking_result struct) throws org.apache.thrift.TException {
        TTupleProtocol iprot = (TTupleProtocol) prot;
        BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = new com.shl.thriftstudy.result.BookingResult();
          struct.success.read(iprot);
          struct.setSuccessIsSet(true);
        }
      }
    }

  }

}
